import { invoke } from "@tauri-apps/api/core";
import type { ArtifactRecord, SourceRecord, WutaiTask } from "../domain/task";
import { appendEvent } from "../domain/task";
import type { ResearchAdapter, TaskUpdateHandler } from "./researchAdapter";

interface GptResearcherSource {
  title?: string;
  url: string;
  note?: string;
}

interface GptResearcherRunOutput {
  report: string;
  sources: GptResearcherSource[];
  audit: unknown;
}

function assertNotAborted(signal: AbortSignal) {
  if (signal.aborted) {
    throw new DOMException("Task cancelled", "AbortError");
  }
}

export const gptResearcherAdapter: ResearchAdapter = {
  backendName: "GPT Researcher sidecar",

  async run(
    initialTask: WutaiTask,
    signal: AbortSignal,
    onUpdate: TaskUpdateHandler,
    artifactWriter,
  ) {
    let task = appendEvent(
      {
        ...initialTask,
        status: "running" as const,
        updatedAt: new Date().toISOString(),
      },
      {
        type: "TaskStepUpdated",
        summary: "Starting GPT Researcher sidecar.",
        details:
          "Wutai will call the local Python adapter and translate the result into task artifacts.",
        visibility: "user",
      },
    );
    await onUpdate(task);

    assertNotAborted(signal);

    task = appendEvent(task, {
      type: "TaskStepUpdated",
      summary: "Running open-source deep research adapter.",
      visibility: "user",
    });
    await onUpdate(task);

    const result = await invoke<GptResearcherRunOutput>("run_gpt_researcher", {
      input: {
        taskId: task.taskId,
        query: task.userRequest,
        reportType: "research_report",
        tone: "objective",
      },
    });

    assertNotAborted(signal);

    const createdAt = new Date().toISOString();
    const sourceRecords: SourceRecord[] = result.sources.map((source, index) => ({
      sourceId: `${task.taskId}_source_${index + 1}`,
      taskId: task.taskId,
      title: source.title?.trim() || source.url,
      url: source.url,
      note: source.note?.trim() || "Captured by GPT Researcher.",
    }));

    const artifacts: ArtifactRecord[] = [
      {
        artifactId: `${task.taskId}_artifact_report`,
        taskId: task.taskId,
        type: "markdown",
        name: "report.md",
        virtualPath: `artifacts/${task.taskId}/report.md`,
        content: result.report,
        createdAt,
      },
      {
        artifactId: `${task.taskId}_artifact_sources`,
        taskId: task.taskId,
        type: "json",
        name: "sources.json",
        virtualPath: `artifacts/${task.taskId}/sources.json`,
        content: JSON.stringify(sourceRecords, null, 2),
        createdAt,
      },
      {
        artifactId: `${task.taskId}_artifact_audit`,
        taskId: task.taskId,
        type: "json",
        name: "audit.json",
        virtualPath: `artifacts/${task.taskId}/audit.json`,
        content: JSON.stringify(
          {
            taskId: task.taskId,
            userRequest: task.userRequest,
            permissions: task.permissions,
            adapter: "gpt-researcher",
            generatedAt: createdAt,
            sidecarAudit: result.audit,
          },
          null,
          2,
        ),
        createdAt,
      },
    ];

    task = {
      ...task,
      status: "completed",
      sources: sourceRecords,
      artifacts,
      updatedAt: createdAt,
    };

    task = await artifactWriter.write(task);

    task = appendEvent(task, {
      type: "ArtifactCreated",
      summary: "Saved GPT Researcher report, sources, and audit artifacts.",
      details: "Artifacts were generated by the GPT Researcher sidecar.",
      visibility: "user",
    });

    task = appendEvent(task, {
      type: "TaskCompleted",
      summary: "Research task completed.",
      visibility: "user",
    });

    await onUpdate(task);
    return task;
  },
};
